[Global]
n_warmup = 1
n_iter = 1
n_trial = 3
check_correctness = true
auto_size = false
models = ["cunumeric", "cupynumeric", "cudajl", "jacc", "dagger"]

[[nas_mg]]
T = "Float64"
gpus = 1
cpus = 8
N = 32
M = 32
kwargs = { class = "S" }
