steps:
  - label: "Setup (Legate)"
    key: setup_legate
    agents:
      queue: "juliagpu"
      cuda: "*"
    commands:
      - julia --project -e 'using Pkg; Pkg.Registry.update();
                          Pkg.add(PackageSpec(url="https://github.com/JuliaLegate/Legate.jl.git", rev="main"));
                          Pkg.instantiate()'
  
  - label: "Julia v1"
    depends_on: setup_legate
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          dirs:
            - src
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 30
    env:
      LEGATE_SHOW_CONFIG: "1"

  - label: "Julia 1.11"
    depends_on: setup_legate
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          dirs:
            - src
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 30
    env:
      LEGATE_SHOW_CONFIG: "1"

  - label: "Julia LTS"
    depends_on: setup_legate
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          dirs:
            - src
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 30
    env:
      LEGATE_SHOW_CONFIG: "1"