steps:
  - label: "Julia v1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          dirs:
            - src
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    command: "julia --project -e 'using Pkg; Pkg.add(;url = \"https://github.com/JuliaLegate/Legate.jl.git\", rev = \"main\")'"
    timeout_in_minutes: 30
    env:
      LEGATE_SHOW_CONFIG: "1"

  - label: "Julia 1.11"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.11"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          dirs:
            - src
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    command: "julia --project -e 'using Pkg; Pkg.add(;url = \"https://github.com/JuliaLegate/Legate.jl.git\", rev = \"main\")'"
    timeout_in_minutes: 30
    env:
      LEGATE_SHOW_CONFIG: "1"

  - label: "Julia LTS"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.10"
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          dirs:
            - src
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    command: "julia --project -e 'using Pkg; Pkg.add(;url = \"https://github.com/JuliaLegate/Legate.jl.git\", rev = \"main\")'"
    timeout_in_minutes: 30
    env:
      LEGATE_SHOW_CONFIG: "1"