cancel_intermediate_builds: true
cancel_running_branch_builds: true


env:
  SECRET_CODECOV_TOKEN: "sMCDyGgkybsZMWSXvJDovbNC38ZMt4NmXzjvCpCxsnd7yXFSI6FpWigltoQafN/HM170MfVarH+sepnEbWOCgDmVzxn+Aolw4nL+o/5Bx1EeG+ztpOShzzaFMyrR8dfcAOr8Syo1O9LYGxP0c01onWGnA5L16Bl2J4gL+6pVPBsZtH57PREoNOPVED2eDw4R/U7MMpA5BCFO+37nNWhsw5+su4OwcTWVPNM8z02LooxL4o6pX3xc11bF7n2kD8NCJDu0hbolimqBXabP2BgHaWYmVe8LiC1b8nIi29ET8/YVxmTSUqj/iYTzIFXKawLB7W7IvTMe6NmSMQIK7Li3xQ==;U2FsdGVkX19XNvaivb92zC6a2SOk1aj3zZ5L1SBhCpVl9LiJdOGEu9wb1boGLyHjk5fSiLzEtEVgd1lvyDO5HuJ07tKLrwBjWQxdS2moeQs="

steps:
  - group: ":julia: Julia"
    key: "julia"
    steps:
      - label: "GPU - Julia {{matrix.julia}}"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - jquick/pre-hook#v1.2.0:
              command: "julia --project -e 'using Pkg; Pkg.add(;url = \"https://github.com/JuliaLegate/Legate.jl\", subdir = \"lib/LegatePreferences\", rev=\"no-cuda\"); Pkg.add(;url=\"https://github.com/JuliaLegate/Legate.jl.git\", rev=\"no-cuda\"); Pkg.instantiate()'"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              dirs:
                - src
                - lib
              codecov: true
        agents:
          queue: "juliagpu"
          cuda: "*"
        if: build.message !~ /\[skip tests\]/
        timeout_in_minutes: 30
        env:
          LEGATE_SHOW_CONFIG: "1"
          GPUTESTS: "1"
        matrix:
          setup:
            julia:
              - "1.10"
              - "1.11"
              - "1.12"
            arch:
              - "x64"
          adjustments:
            - with:
                julia: "1.12"
              soft_fail : true

  # - group: ":computer: CUDA Versions (Julia 1.11)"
  #   key: "cuda"
  #   depends_on: "julia"
  #   steps:
  #     - label: "Julia 1.11 CUDA {{matrix.cuda}}"
  #       plugins:
  #         - JuliaCI/julia#v1:
  #             version: "1.11"
  #         - jquick/pre-hook#v1.2.0:
  #             command: "julia --project -e 'using Pkg; Pkg.add(;url=\"https://github.com/JuliaLegate/Legate.jl.git\", rev=\"main\");  Pkg.instantiate()'"
  #         - JuliaCI/julia-test#v1:
  #             test_args: "--quickfail"
  #       agents:
  #         queue: "juliagpu"
  #         cuda: "{{matrix.cuda}}"
  #       if: build.message !~ /\[skip tests\]/
  #       timeout_in_minutes: 30
  #       env:
  #         LEGATE_SHOW_CONFIG: "1"
  #         GPUTESTS: "1"
  #       matrix:
  #         setup:
  #           cuda:
  #             - "12.2"
  #             - "12.4"
  #             - "13.0"
  #           arch:
  #             - "x64"
  #         adjustments:
  #           - with:
  #               cuda: "13.0"
  #             soft_fail: true
  #       commands: |
  #         echo -e "[CUDA_Runtime_jll]\nversion = \"{{matrix.cuda}}\"" >LocalPreferences.toml
