cancel_intermediate_builds: true
cancel_running_branch_builds: true

env:
  SECRET_CODECOV_TOKEN: "iYDXbmzSsj91jFiZQl79SeRZb9u7I5zXVlsGG3bZdHPw3PW2JZPNRcIC6tLxYmmRL8oSPyg6mIe6wrrkNmuHo54sUrWOrafGBil1xxKinZDUaGUaF9OvPx96tDT92USAYHZkYl7us+js/4rzx03cyHU0d2n9qjapb8UzWi3Mji3WIuI5nC5B8+PZSiyxXlBYt8DupvBDsdrMLNkCNpG39ZKTIk0q/nFoFUtiLhh6lum2cS4d57VXNl/LSHEJykqqyW2ivpo/ms25RHoHpp0gjDCxp7a1fZ8+wjHwEcf1nxpZ886SKEyc/Zv6QaenvX9J8EuJLPAfKj7oYDmAtlwK6Q==;U2FsdGVkX19wPGBxZZObzZ/gF0hPIup/8wf55LEGnXlXjqxNGMhOR0PyUpWVCiXIj8AIcui4gRmge/o+op4qYg=="

steps:
  - group: ":julia: Julia"
    key: "julia"
    steps:
      - label: "GPU - Julia {{matrix.julia}}"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - jquick/pre-hook#v1.2.0:
              command: "julia --project -e 'using Pkg; Pkg.add(;url=\"https://github.com/JuliaLegate/Legate.jl.git\"); Pkg.instantiate()'"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              dirs:
                - src
              codecov: true
        agents:
          queue: "juliagpu"
          cuda: "*"
        if: build.message !~ /\[skip tests\]/
        timeout_in_minutes: 45
        env:
          LEGATE_SHOW_CONFIG: "1"
          GPUTESTS: "1"
          LEGATE_TEST: "1"
        matrix:
          setup:
            julia:
              - "1.10"
              - "1.11"
              # - "1.12"
            arch:
              - "x64"
          # adjustments:
          #   - with:
          #       julia: "1.12"
          #     soft_fail : true

  # - group: ":computer: CUDA Versions (Julia 1.11)"
  #   key: "cuda"
  #   depends_on: "julia"
  #   steps:
  #     - label: "Julia 1.11 CUDA {{matrix.cuda}}"
  #       plugins:
  #         - JuliaCI/julia#v1:
  #             version: "1.11"
  #         - jquick/pre-hook#v1.2.0:
  #             command: "julia --project -e 'using Pkg; Pkg.add(;url=\"https://github.com/JuliaLegate/Legate.jl.git\", rev=\"main\");  Pkg.instantiate()'"
  #         - JuliaCI/julia-test#v1:
  #             test_args: "--quickfail"
  #       agents:
  #         queue: "juliagpu"
  #         cuda: "{{matrix.cuda}}"
  #       if: build.message !~ /\[skip tests\]/
  #       timeout_in_minutes: 30
  #       env:
  #         LEGATE_SHOW_CONFIG: "1"
  #         GPUTESTS: "1"
  #       matrix:
  #         setup:
  #           cuda:
  #             - "12.2"
  #             - "12.4"
  #             - "13.0"
  #           arch:
  #             - "x64"
  #         adjustments:
  #           - with:
  #               cuda: "13.0"
  #             soft_fail: true
  #       commands: |
  #         echo -e "[CUDA_Runtime_jll]\nversion = \"{{matrix.cuda}}\"" >LocalPreferences.toml
