cancel_intermediate_builds: true
cancel_running_branch_builds: true

env:
  SECRET_CODECOV_TOKEN: "V6sJ4HBJT+E4RtciX9fbkyUjVgOrt94J5Z/XSk5YHXIZ4Lm8Of1mna4zeKAciVYmKyat8cHbTAUXAC6Px1PBnOvBK1NbJpP48kXUk46fECyfyCoa9hkqdxWJPFE6EFjNL3s+wWS+nRjEle73wI2MFrRjn3z4D5g9vcW7Kxdl2wsxm2uXAE2atLFN5rli/msLYe4591VP1GRYUB+03KIg/A+2tuL3EvQk76m0qGSIU43lVMp5lO+aVhz/2EieVufnT/COZbCw4g2SEqqYNi7j24Hrgc19T/e1jY7OaCdiX4Q7Nf35UTapxHDZVPTeJageHm9wEDqlL54Y6+Mmy9h7cw==;U2FsdGVkX180zv9chFTpgUljSesITPZu2XDdFqJFZHrSumfFlATifq2KvBmgQoh1WyYwPlf7QtTwqkZt9Tw/iw=="

steps:
  - group: ":julia: Julia"
    key: "julia"
    steps:
      - label: "GPU - Julia {{matrix.julia}}"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - jquick/pre-hook#v1.2.0:
              command: "julia --project -e 'using Pkg; Pkg.add(;url=\"https://github.com/JuliaLegate/Legate.jl.git\"); Pkg.instantiate()'"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              dirs:
                - src
              codecov: true
        agents:
          queue: "juliagpu"
          cuda: "*"
        if: build.message !~ /\[skip tests\]/
        timeout_in_minutes: 45
        env:
          LEGATE_SHOW_CONFIG: "1"
          GPUTESTS: "1"
          LEGATE_TEST: "1"
          LEGATE_CONFIG: "--cpus 1 --gpus 1 --utility 1 --fbmem 2000"
        matrix:
          setup:
            julia:
              - "1.10"
              - "1.11"
              # - "1.12"
            arch:
              - "x64"
          # adjustments:
          #   - with:
          #       julia: "1.12"
          #     soft_fail : true

  # - group: ":computer: CUDA Versions (Julia 1.11)"
  #   key: "cuda"
  #   depends_on: "julia"
  #   steps:
  #     - label: "Julia 1.11 CUDA {{matrix.cuda}}"
  #       plugins:
  #         - JuliaCI/julia#v1:
  #             version: "1.11"
  #         - jquick/pre-hook#v1.2.0:
  #             command: "julia --project -e 'using Pkg; Pkg.add(;url=\"https://github.com/JuliaLegate/Legate.jl.git\", rev=\"main\");  Pkg.instantiate()'"
  #         - JuliaCI/julia-test#v1:
  #             test_args: "--quickfail"
  #       agents:
  #         queue: "juliagpu"
  #         cuda: "{{matrix.cuda}}"
  #       if: build.message !~ /\[skip tests\]/
  #       timeout_in_minutes: 30
  #       env:
  #         LEGATE_SHOW_CONFIG: "1"
  #         GPUTESTS: "1"
  #       matrix:
  #         setup:
  #           cuda:
  #             - "12.2"
  #             - "12.4"
  #             - "13.0"
  #           arch:
  #             - "x64"
  #         adjustments:
  #           - with:
  #               cuda: "13.0"
  #             soft_fail: true
  #       commands: |
  #         echo -e "[CUDA_Runtime_jll]\nversion = \"{{matrix.cuda}}\"" >LocalPreferences.toml
