name = "cuNumeric"
uuid = "0fd9ffd4-7e84-4cd0-b8f8-645bd8c73620"
authors = ["ejmeitz <emeitz@andrew.cmu.edu>"]
version = "0.0.1"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"

[compat]
julia = "1.10"
CxxWrap = "0.16"
