name: Documentation

on:
  push:
    branches:
      - init_docs # update when i know it works
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'
      - name: Install docs dependencies
        run: julia --project=pkg/docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=joinpath(pwd(),"pkg","docs"))); Pkg.instantiate()'
      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=pkg/docs/ pkg/docs/make.jl